# Generated by Django 4.2.3 on 2023-08-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='componenetValue',
            new_name='componentValue',
        ),
    ]
